### ISSUE TITLE
Create gripper for Niryo One based on the Niryo Ned's gripper

### ISSUE THREAD

**Issue by quangnhat185** [hsrwrobotics/niryo_one_ros#4]
Refer to Niryo Ned gripper file [here](https://github.com/NiryoRobotics/ned_ros/blob/master/niryo_robot_description/urdf/ned/niryo_ned_gripper1_n_camera.urdf.xacro)

**Comment by mtc-20** [comment]
STL files for all **Niryo One** tools can be found [here](https://github.com/NiryoRobotics/niryo_one/tree/master/STL/7-Tools)
 - would be cool to implement these for future releases

**Comment by mtc-20** [comment]
- URDF of **Niryo One** has been added to [v2](https://github.com/hsrwrobotics/niryo_one_ros/tree/master/niryo_one_description/urdf/v2)
  - corresponding STL files have been added to `meshes` in the repo as well 


New issues to be raised to provide additional support/capabilities
- controllers for `gripper`
- arguments to gazebo launch file to choose urdf model
